name: ci_check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: deploy-app-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: deploy
        run: yarn install && yarn deploy
