name: deploy_app

on:
  push:
    branches:
      - master

concurrency:
  group: deploy-app-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: deploy
        run: |
          git config --global user.email "stodyshev@gmail.com"
          git config --global user.name "SergeyT Github Automation"
          yarn install
          yarn deploy
